### ISSUE TITLE
Entry BackgroundColor

### ISSUE THREAD

**Issue by mtugnoli** [ewerspej/maui-samples#1]
This property seem not run in Entry controls with dark/light mode...

**Comment by ewerspej** [comment]
Thanks for letting me know, I might have missed setting up the colors correctly. I will check it out. It might also be a bug in .NET MAUI, in the latter case, you could check the official MAUI GitHub repository and file an issue if one doesn't already exist for it.

**Comment by ewerspej** [comment]
@mtugnoli There seems to be an issue with the colors of the Entry control in MAUI when using `AppThemeBinding`.

**Comment by mtugnoli** [comment]
I see... also in picker controls, just wainting a MAUI update :(

**Comment by ewerspej** [comment]
Yep. I only used the default settings. If something regarding the `AppThemeBinding` isn't working, then it's most likely a bug in MAUI.
